### ISSUE TITLE
Allow subject to initiate a rectification from the frontend UI

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#284]
**Is your feature request related to a problem? Please describe.**
A subject can not rectify his data from the UI.

**Describe the solution you'd like**
A subject should be able to initiate a rectification from the frontend UI. 

Since the data is free and independent per Controller, for now, and just addressing a way to edit before we solve how to specify the data schema from the Controller's side, having a JSON editor component is enough to start building a functional MVP.

https://www.npmjs.com/package/react-json-editor-ajrm

**Describe alternatives you've considered**
As an alternative, defining the schema in the Controllers configuration makes sense but is to much work right now. We need just to link the SDK with the elements.

**Additional context**
None.

**Comment by fjcero** [comment]
As you said @segoddnja data requested for a Controller is treated as a free JSON object. The thing is that Elements SDK depends inherently from Controller's configuration so we can specify somewhere in the backend which data could be rectified, the same way that the Controller ask to collect. This task will required some extra work from the API point of view, but that is how other companies are doing it. 

When we have this configuration we can render a pretty form, but for now, a Json Editor input will be enough since we're not releasing this to customers, better to have a component working and then we will improve it. Some lib like this will be helpful https://www.npmjs.com/package/react-json-editor-ajrm

**Comment by segoddnja** [comment]
@fjcero Well, we are going to include Elements SDK into the initial release. So I don't think json editor is appropriate solution. But, we definitely can limit a set of data field types to a certain number - lets say to allow to use only text inputs, dropdowns, checkboxes, radio buttons and textareas. So we can render form in this case.

**Comment by Nelrohd** [comment]
Let's discuss about the smaller tasks
