### ISSUE TITLE
Set up processor outside existing cluster to test / prove the system works

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#309]
**Is your feature request related to a problem? Please describe.**
ClearGDPR never tried to add a processor outside of the existing cluster.

**Describe the solution you'd like**
- [x] Set up a processor node outside our cluster.
- [x] Add the processor created outside our local cluster to the Quorum blockchain network.

*UPDATE:*I will create a separate task for the automation, for it is quite complex.

@sindelio Please complete if you get more informations.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by sindelio** [comment]
We must have a processor (Quorum node) outside our local cluster to be able to test the back-end API in a production environment and make sure it works.
First thing to do here is ask devops how to set up a processor.

**Comment by Nelrohd** [comment]
I think this task isn't very clear to me. Do we know the list of the steps required? Right now the only one is "Asking devops how to setup a processor".

**Comment by segoddnja** [comment]
As I understand the problem, it is not possible to add new nodes to cluster because contract is deployed as private. I am pretty new in blockchain stuff and do not know what is the difference. @sindelio Can you clarify this? Do we really need it to be private?

**Comment by Nelrohd** [comment]
@sindelio Add how do we validate that it works. Kpis?

**Comment by Nelrohd** [comment]
Why do we use private contract? Why not public? @sindelio

**Comment by Nelrohd** [comment]
Let's list the pros & cons for both then.

**Comment by sindelio** [comment]
These are the steps to add an outsider quorum node to our local cluster:

1. Stand up a local quorum cluster
2. Stand up a node using geth init + static-nodes file with ALL the other nodes in the cluster as set up in #1
Populate the static-nodes.json file with all other nodes in the cluster you are joining
3. Start geth node and get its enode url. (We don't need to star it actually, we just need to know it's enode, which can be found inside it's configuration files)
4. On ANY of the nodes in #1 run raft.addPeer($enode)
5. Start the new node again with --raftjoinexisting ID
step #5 will connect the new node to the entire cluster. Key here is to make sure the static-nodes is up to date with ALL existing nodes in the cluster
6. admin.addPeer($enode) wont be needed if this sequence

Got this information on the official Quorum slack channel

**Comment by sindelio** [comment]
I checked the raft.addPeer($enode) function and the raft object is not defined in our current Quorum version. We need to update Quorum to v2 and set the -rpcapi switch.
Our next step should be changing the images to have the latest Quorum in them.

**Comment by sindelio** [comment]
Also, I will have more meetings with Maks to continue transfering knowledge and discussing about this challenging task. @Nelrohd @segoddnja you should participate in those discussions as well. The next one will be Monday probably

**Comment by sindelio** [comment]
Maks helped me to understand why the raft management API wasn't showing up!
We had to rebuild the Quorum image used for the project, and after that it worked :))
So now we're starting tests in adding/removing nodes dynamically!

**Comment by sindelio** [comment]
THIS COMMENT DOCUMENTS HOW TO SET UP A PROCESSOR NODE OUTSIDE OUR LOCAL QUORUM CLUSTER.

What was done:

1. Create a separate Docker image (named quorum_processor) for the processors. The easiest way to it is with the following commands (inside the ./quorum/ subfolder):

```docker login```  
This logs into Docker Hub. Currently only I have access to the account there, so if anything is needed regarding the project Docker images either ask me or reach out to devops.

  ```docker build -t cleargdpr/quorum_processor:0.0.n .``` 
This command builds the image based in the Dockerfile inside the folder, names it quorum_processor, adds it to the cleargdpr repo in Docker Huband tags it with 0.0.n version. Substitute n according to the current version.
Dont' forget the dot in the end of the command!

```docker push cleargdpr/quorum_processor:0.0.n```
This command pushes the created image to the Docker Hub repo.

This image has changes inside it which are specific for a processor node. In particular, the startup command was changed (the CMD line in the end of the image).

2. Set the services regarding the processor to use the new quorum_processor image. They are: contellation2 and geth2.

3. Update the setup.js file to create the environment needed for an outsider processor. Basically we must have each quorum node with only their own enode inside their static-nodes.json file. This means that they are effectively separated and don't have connectivity via their Geth nodes. The controller and the processor were separated because we want to test adding a node dynamically.

**Comment by sindelio** [comment]
THIS COMMENT DOCUMENTS HOW TO CONNECT A QUORUM NODE DYNAMICALLY TO AN EXISTING NETWORK.

1. Read the enode of the outsider quorum node (processor). This has to be done WITHOUT STARTING THE OUTSIDER NODE. That is, the command that starts the Geth node can't be executed yet. Since we are starting all services at once, this means we should not run ```docker/run```. The enode can be found in the static-nodes-entry file, inside the quorum subfolder.

2. Start the quorum controller node. After is starts, open up a JS console inside the running Geth node:

```docker-compose exec geth1 attach ws://quorum1:8546```

3. Add the outsider quorum node to the local cluster:

```raft.addPeer($outsider_processor_enode)```
The outsider_processor_enode is the enode read in setp 1. This function will return a raft ID, which has to be used by the outsider processor in the next step.

4. Start the outsider processor with the raft ID got from the controller in step 3. The processor's Geth node has to be started with the following flag:

```--raft --raftjoinexisting raftId```
The raftId is the one returned by raft.addPeer($_outsider_processor_enode) in step 3. The complete startup command for the outsider processor is:

```PRIVATE_CONFIG=/qdata/tm.conf /usr/local/bin/geth --datadir /qdata/dd --raft --raftjoinexisting 2 --rpc --rpcaddr 0.0.0.0 --port "$ETH_PORT" --ws --wsorigins="*" --wsaddr 0.0.0.0 --wsport "$WEBSOCKET_PORT" --rpcport "$RPC_PORT" --raftport "$RAFT_PORT" --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,raft --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,raft --nodiscover --unlock 0 --password /qdata/passwords.txt```
 
That's it, now the Geth nodes should syncronize and exchange data over an HTTP port. This also implicates that the Constellation nodes can communicate to each other now. Remembring: Geth and Constellation are different nodes, and they both are components of the Quorum node.
