### ISSUE TITLE
Erased subject has still access to the system

### ISSUE THREAD

**Issue by sindelio** [ClearGDPR/ClearGDPR#342]
**Describe the bug**
After a subject's data is erased, he still has full access to the system

**To Reproduce**
1. Start up the system
2. Go to Postman
3. in the DEMO API, register a subject. Copy the cgtoken returned to the environment as the subject JWT. (Top right of the screen)
4. Go to the CG API, in the subjects section, give consent for that subject
5. Verify that the subject has given consent with the GET endpoints
6. Erase the subject fro the system
7. Try to read the erased subject's data, get objections, get restrictions and so on

**Expected behavior**
After a subject's data is erased, he should not be able to do anything in the system.

**Screenshots**
None.

**Additional context**
@Nelrohd @segoddnja you guys can think about what an erased subject should be able to do in the system. At first I would say not much.

**Comment by sindelio** [comment]
I checked what happens when the subject erases his data, and he still can do almost anything in the system. I will fix this, I think a small middleware called "notErased" will do it

**Comment by segoddnja** [comment]
As I understand this task is about "right to be forgotten" implementation. As for me this is one of the most challenging tasks. Few links:
- https://gdpr-info.eu/art-17-gdpr/
- https://gdpr-info.eu/issues/right-to-be-forgotten/
- https://ec.europa.eu/info/law/law-topic/data-protection/reform/rules-business-and-organisations/principles-gdpr/how-long-can-data-be-kept-and-it-necessary-update-it_en

So in short, there are few keypoints.

**data must be erased immediately**

That's clear, that Controller and Processors must erase data ASAP once they receive request from Subject and confirm that this request is legal. So, any API endpoints must return 404 when the erased data is requested.

**Do not keep data longer than it is necessary for processing purposes.**

Processors must report to Controller that they have already processed and erased data because no longer need it. So Controller, in case it does no longer need this data as well for some other purposes, must erase data. ClearGDPR can provide a system of hooks. So Controller will be able to configure hook which fires when usages count of certain type data record becomes 0.
 
**Erase data everywhere, even in backups**

We do not care how do processors store and erase data, we only need to receive confirmation that data is erased. But, we do care how Controller does it. And there couldn't be any general-purpose solution because data storage is not a part of ClearGDPR. Each Controller adopting ClearGDPR must implement it on it's own. We can only provide a way to write to the log.

**An application of erasure is not subject to any particular form, and the responsible party need not link it to such a form. However, the identity of the impacted person must be proven in a suitable way, as otherwise additional information could be requested from the responsible party, or the erasure could be refused.**

It depends on the Controler what way it provides for Subjects to exercise the right. ClearGDPR provides either Element SDK or JS SDK to implement this. But, ClearGDPR may need to provide a ways to work with different scenarios. It is possible that there is no web application at all. So data is collected in the Controller company's office, Subject does a phone call to exercise his right. A way to register such event in the log  and a way to instantiate data erasure from admin section may be necessary.

**Article 17, paragraph 3**

Sometime it is not possible to erase data immediately. It is also not possible to provide general-purpose solution for this. We can provide specific event type, like `DataArchived`, and provide API endpoint to record it to log.

**Comment by Nelrohd** [comment]
Let's plan a discussion for it

**Comment by sindelio** [comment]
This task will require a middleware for express, named 'notErased', which should check if the subject in question is erased or not in the system. This middleware should be used in the endpoints of the subjects, in subjects.routes, inside the subjects domain. Maybe somewhere else too? Have to take a look closer to the code to see.
