### ISSUE TITLE
Suggestions of features & improvements

### ISSUE THREAD

**Issue by Nelrohd** [ClearGDPR/ClearGDPR#355]
@sindelio @fjcero @juanmnl Since you have experience in this project, could you, each of you, add in this ticket a list of features and improvements that you would like to see in the short and mid future (weeks to months).

Thank you!

**Comment by fjcero** [comment]
**Short-term**
- Demo should be more like a guided tour flow
- Documentation on API and SDK should be easier to follow/share
- Elements SDK should be seamless to integrate in existent blogs/sites via opt-in for accepting data sharing
- Add more rights management support for Subjects

**Mid-term**
- CG Wizard: A tutorial/interactive script on how to setup the platform in AWS, Heroku, k8s or similar
- Wordpress plugin continuing with SDK seamless integration
- Cover more Controller and Processors flows in the platform
- Research if there is a way to use SDK to create middlewares for backend services

**Long-term**
- Provide a hosted version of the service form small companies/users
- Research for SSO integrations: since identity will be fully managed by Processors, having an standarized way of integration will be interesting
- Research for DPO (Data Processing Officers) is useful for enterprise candidates

**Comment by sindelio** [comment]
**Short-term**
- Set another processor outside our local cluster
- Implement private smart contract between specific nodes, one node being outside the local cluster we have
- Implement upgradeability for the smart contract
- Add and remove nodes dynamically in the Quorum network
- Check and fix the interaction between the rights implemented

**Mid-term**
- Better handle memory allocation in the smart contract
- Handle the transactions that involve the database and the smart contract properly
- Refactor the processors listeners
- Handle any refactor or bug left
- Start the blogging campaign 
- Research on data retention periods

**Long-term**
- Heavy marketing campaign for the project adoption
- Get feedback from clients and users

**Comment by Nelrohd** [comment]
Thank you all, amazing feedback!
